export const logo: string;
export const header: string;
export const headerTrigger: string;
export const footer: string;
export const content: string;
export const pageHeader: string;
export const pageHeaderBreadcrumb: string;
export const pageHeaderDetail: string;
export const pageHeaderTitle: string;
